import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Navbar } from "../components/Navbar";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [position, setPosition] = useState<GeolocationPosition | null>(null);
  const getLocationData = trpc.useQuery(
    [
      "weather.getData",
      {
        lat: position?.coords.latitude,
        long: position?.coords.longitude,
      },
    ],
    {
      retry: false,
    }
  );
  const getPosition = () => {
    if ("geolocation" in navigator) {
      const pos = navigator.geolocation.getCurrentPosition(
        (currentPosition) => {
          setPosition(currentPosition);
        }
      );
    } else {
      console.log("geolocation access is required !");
    }
  };

  useEffect(() => {
    getPosition();
  }, []);

  return (
    <>
      <Head>
        <title>OpenWeather API WEB APP WITH NEXTJS + TYPESCRIPT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container p-3">
        <div className="container shadow-md">
          <h2>Lat : {position?.coords.latitude}</h2>
          <h2>Long: {position?.coords.longitude}</h2>
        </div>
        <div className="container shadow">
          <h1 className="text-2xl">Today Forecast</h1>
          <h1 className="text-2xl">{getLocationData.data?.name}</h1>
        </div>
      </main>
    </>
  );
};

export default Home;
